#ifndef DEF_MOGUSHAN_VAULTS_H_
#define DEF_MOGUSHAN_VAULTS_H_

#define MAX_ENCOUNTERS 6

enum Creatures
{
	BOSS_ELEGON   = 60410,
    BOSS_FENG_THE_ACCURSED   = 60009,
    BOSS_GARAJAL_THE_SPIRITBINDER   = 60143,
	BOSS_THE_SPIRIT_KINGS = 61421,
	BOSS_WILL_OF_THE_EMPEROR = 60400,
	BOSS_THE_STONE_GUARD = 60047,
};

enum Objects
{
    
};

enum Data
{   
	DATA_THE_STONE_GUARD = 1,
    DATA_FENG_THE_ACCURSED   = 2,
    DATA_GARAJAL_THE_SPIRITBINDER   = 3,
	DATA_THE_SPIRIT_KINGS = 4,
	DATA_ELEGON   = 5,
	DATA_WILL_OF_THE_EMPEROR = 6,	
};

#endif
