/* # Script de Sungis : Mogu'shan Vaults # */

#ifndef DEF_MOGUSHAN_VAULTS_H
#define DEF_MOGUSHAN_VAULTS_H

enum Creatures
{
	BOSS_AMETHYST_GUARDIAN			= 60047,
	BOSS_COBALT_GUARDIAN			= 60051,
	BOSS_JADE_GUARDIAN				= 60043,
	BOSS_JASPER_GUARDIAN			= 59915,
	BOSS_FENG_THE_ACCURSED			= 60009,
	BOSS_GARAJAL_THE_SPIRITBINDER	= 60143,
	BOSS_ZIAN						= 61421,
	BOSS_MENG						= 60708,
	BOSS_QIANG						= 60709,
	BOSS_SUBETAI					= 60710,
	BOSS_ELEGON						= 60410,
	BOSS_JAN_XI						= 60400,
	BOSS_QIN_XI						= 60399,
};

enum Data64
{
	DATA_THE_STONE_GUARD,
	DATA_AMETHYST_GUARDIAN,
	DATA_COBALT_GUARDIAN,
	DATA_JADE_GUARDIAN,
	DATA_JASPER_GUARDIAN,
	DATA_FENG_THE_ACCURSED,
	DATA_GARAJAL_THE_SPIRITBINDER,
	DATA_ZIAN,
	DATA_MENG,
	DATA_QIANG,
	DATA_SUBETAI,
	DATA_ELEGON,
	DATA_WILL_OF_THE_EMPEROR,
	DATA_JAN_XI,
	DATA_QIN_XI,
};

#endif
