/* Script de Tydrheal : Temple du serpent de jade. */

#ifndef DEF_TEMPLE_OF_THE_JADE_SERPENT_H
#define DEF_TEMPLE_OF_THE_JADE_SERPENT_H

enum Data64
{
	DATA_BOSS_WISE_MARI,
	DATA_BOSS_LOREWALKER_STONESTEP,
	DATA_NPC_ZAO_SUNSEEKER,
	DATA_NPC_CORRUPTED_SCROLL,
	DATA_NPC_SUN_1,
	DATA_NPC_SUN_2,
	DATA_NPC_SUN_3,
	DATA_NPC_SUN_4,
	DATA_NPC_SUN_5,
	DATA_BOSS_LIU_FLAMEHEART,
	DATA_BOSS_SHA_OF_DOUBT
};

enum CreaturesIds
{
	BOSS_WISE_MARI				= 56448,
	BOSS_LOREWALKER_STONESTEP	= 56843,
	NPC_ZAO_SUNSEEKER			= 58826,
	NPC_CORRUPTED_SCROLL		= 57080,
	BOSS_LIU_FLAMEHEART			= 56732,
	BOSS_SHA_OF_DOUBT			= 56439

};

enum CreaturesGUID
{
	NPC_SUN_1			= 000000,
	NPC_SUN_2			= 000001,
	NPC_SUN_3			= 000002,
	NPC_SUN_4			= 000003,
	NPC_SUN_5			= 000004,
};


#endif
