/* Script de Tydrheal & Sungis : Temple du serpent de jade. */

#ifndef DEF_TEMPLE_OF_THE_JADE_SERPENT_H
#define DEF_TEMPLE_OF_THE_JADE_SERPENT_H

enum Data64
{
	DATA_BOSS_WISE_MARI,
	DATA_WISE_MARI_GATE,
	DATA_BOSS_LOREWALKER_STONESTEP,
	DATA_NPC_ZAO_SUNSEEKER,
	DATA_NPC_CORRUPTED_SCROLL,
	DATA_NPC_SUN_1,
	DATA_NPC_SUN_2,
	DATA_NPC_SUN_3,
	DATA_NPC_SUN_4,
	DATA_NPC_SUN_5,
	DATA_BOSS_LIU_FLAMEHEART,
	DATA_BOSS_SHA_OF_DOUBT
};

enum GameObjects
{
	GO_WISE_MARI_GATE	= 400428,
};

#endif

